name: Release

on:
  push:
    paths: [CHANGELOG.md]
    branches: [main]
  pull_request:
    paths: [CHANGELOG.md]
    branches: [main]

permissions:
  contents: write

jobs:
  publish:
    uses: ipdxco/changelog-driven-release/.github/workflows/pr.yml@v1
